title: NaN
email: nan@notanumber.io
description: >
  programming, tech, photography, life
baseurl: ''
url: https://notanumber.io
timezone: America/Toronto
permalink: /:year-:month-:day/:title/
paginate: 5
excerpt_separator: <!--more-->

twitter:
  username: nanzhong

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

theme: jekyll-theme-nan

# Build settings
markdown: kramdown
highlighter: rouge

# Theme specific
author:
  name: Nan Zhong
  github: nanzhong
  500px: notanumber
  twitter: nanzhong
  linkedin: nine27

google-analytics:
  id: UA-88257352-1

disqus:
  id: not-a-number.disqus.com

add-this:
  id: ra-583f9ac37995ee1b

nav:
  - name: "About"
    url: "/about/"
  - name: "Archive"
    url: "/archive/"
  - name: "Tags"
    url: "/tags/"

exclude:
  - Gemfile
  - Gemfile.lock
  - notanumber.k8s.yml
  - .deploy.yml
