title: NaN
email: nan@notanumber.io
description: > 
  programming, tech, photography, life
baseurl: ''
url: https://notanumber.io
timezone: America/Toronto
permalink: /:year-:month-:day/:title/
paginate: 5
excerpt_separator: <!--more-->

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: nanzhong/jekyll-theme-nan

# Build settings
markdown: kramdown
highlighter: rouge

# Theme specific
author:
  name: Nan Zhong
  github: nanzhong
  500px: notanumber
  twitter: nanzhong
  linkedin: nine27

google-analytics:
  id: UA-88257352-1

disqus:
  id: not-a-number.disqus.com

add-this:
  id: ra-50b3b21426f614c0

nav:
  - name: "About"
    url: "/about/"
  - name: "Archive"
    url: "/archive/"
  - name: "Tags"
    url: "/tags/"
