title: NaN
email: nan@notanumber.io
description: > 
  programming, tech, photography, life
baseurl: ''
url: https://notanumber.io
timezone: America/Toronto
permalink: /:year-:month-:day/:title/
paginate: 5

gems:
  - jekyll-seo-tag
  - jekyll-paginate

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-nan-theme

# Theme specific
author:
  name: Nan Zhong
  github: nanzhong

google-analytics:
  id: UA-88257352-1

disqus:
  id: not-a-number.disqus.com

add-this:
  id: ra-50b3b21426f614c0

nav:
  - name: "About"
    url: "/about/"
  - name: "Archive"
    url: "/archive/"
  - name: "Tags"
    url: "/tags/"
